ORACLE_DIR=/opt/app
ORACLE_BASE=$ORACLE_DIR/oracle
ORACLE_HOME=$ORACLE_BASE/product/11.2.0/db_1
ORACLE_INVENTORY=$ORACLE_DIR/oraInventory
ORACLE_PASSWORD=password1 # for both dba and sys
ORACLE_OPTION=INSTALL_DB_SWONLY
ORACLE_LANGUAGE=en
ORACLE_CHARSET=WE8ISO8859P15
ORACLE_EDITION=EE
ORACLE_HOST_NAME=`hostname -s`
ORACLE_SID=develop
ORACLE_DBNAME=develop
ORACLE_U_USER=oracle
ORACLE_U_PASSWORD=marlo12
ORACLE_G_OINSTALL=oinstall
ORACLE_G_DBA=dba
ORACLE_INSTALL_DIR=$ORACLE_DIR/install

ORACLE_SW_NAME=linux.x64_11gR2_database
ORACLE_SW_DIR=/opt/init.d/software
ORACLE_RSP_DIR=/opt/init.d/ora11gr2
JAVA_SW_NAME=jdk-7u65-linux-x64.tar.gz
ORACLE_RSP_INSTALL=$ORACLE_RSP_DIR/template_11gR2_db_install.rsp
ORACLE_RSP_NETCA=$ORACLE_RSP_DIR/template_11gR2_netca.rsp
ORACLE_RSP_DBCA=$ORACLE_RSP_DIR/template_11gR2_dbca.rsp
ORACLE_T_TNSNAMES=$ORACLE_RSP_DIR/template_tnsnames.ora
ORACLE_T_SQLNET=$ORACLE_RSP_DIR/template_sqlnet.ora
ORACLE_TNSNAMES=$ORACLE_HOME/network/admin/tnsnames.ora
ORACLE_SQLNET=$ORACLE_HOME/network/admin/sqlnet.ora
ORACLE_SERVICE_SCRIPT=$ORACLE_RSP_DIR/service_oracle.sh

SYSTEM_U_USER=ywang
SYSTEM_U_PASSWORD=marlo12

JAVA_HOME=/opt/jdk1.7.0_65